# CONSTANTS
BYTE_ORDER = "little"  # ASR uses little endian
# === === ===
INT64_SIZE = 8
INT32_SIZE = 4
INT16_SIZE = 2
WORD_SIZE = 4
__BI = 1024
KIBI_BYTE = __BI
MEBI_BYTE = __BI * KIBI_BYTE
GIBI_BYTE = __BI * MEBI_BYTE
