# CONSTANTS
BYTE_ORDER = "little"  # ASR uses little endian
# === === ===
INT64_SIZE = 8
FLOAT64_SIZE = INT64_SIZE
INT32_SIZE = 4
FLOAT32_SIZE = INT32_SIZE
INT16_SIZE = 2
FLOAT16_SIZE = INT16_SIZE
INT8_SIZE = 1

WORD_SIZE = 4
__BI = 1024
KIBI_BYTE = __BI
MEBI_BYTE = __BI * KIBI_BYTE
GIBI_BYTE = __BI * MEBI_BYTE
